import localFont from "next/font/local";
import { Inter, Forum, Caveat } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import "@uploadthing/react/styles.css";
import "./globals.css";
import "./ea-grid.css";
import "./main.scss";
import { AuthProvider } from "./Providers";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "sonner";

export const dynamic = "force-dynamic";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const forum = Forum({
  subsets: ["latin"],
  weight: "400",
  //display: "swap",
  //👇 Add variable to our object
  variable: "--font-forum",
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: "400",
  //display: "swap",
  //👇 Add variable to our object
  variable: "--font-caveat",
});

const MightyRiver = localFont({
  src: "./../../public/fonts/Mighty-River.ttf",
  variable: "--font-mighty-river",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta httpEquiv="Pragma" content="no-cache" />
        <meta httpEquiv="Expires" content="-1" />
      </head>

      <body
        className={`${forum.variable} ${GeistSans.variable} ${caveat.variable} ${inter.variable}`}
      >
        <AuthProvider>
          <NextSSRPlugin
            /**
             * The `extractRouterConfig` will extract **only** the route configs
             * from the router to prevent additional information from being
             * leaked to the client. The data passed to the client is the same
             * as if you were to fetch `/api/uploadthing` directly.
             */
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
